[package]
name = "rttx-proto"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
prost.workspace = true
bytes.workspace = true
uuid.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[build-dependencies]
prost-build.workspace = true
