[package]
name = "rttx-proto"
version = "0.2.1"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
prost = { version = "0.13", features = ["std", "prost-derive"] }
bytes = "1"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[build-dependencies]
prost-build = "0.13"
