#!/usr/bin/env bash
# Build an rttx source RPM (SRPM) from the current git checkout.
#
# The SRPM is the one artifact that every Fedora release can be built from:
# feed it to `mock -r <chroot>` locally or to `copr-cli build` and each target
# (fedora-43, fedora-44, rawhide, x86_64, aarch64, ...) compiles it natively.
#
# Steps:
#   1. source tarball  — `git archive HEAD` (committed files only!)
#   2. vendor tarball  — `cargo vendor` of the exact Cargo.lock, so rpmbuild
#                        needs no network (mock/COPR builders are offline)
#   3. rpmbuild -bs    — pack 1 + 2 + rttx.spec into rttx-<ver>-<rel>.src.rpm
#   4. (optional) mock — rebuild the SRPM for each requested chroot
#
# Usage:
#   packaging/rttx/rpm/build-srpm.sh [options]
#     --outdir DIR        where to put the SRPM (default: target/rpmbuild)
#     --mock CHROOTS      comma-separated mock chroots to rebuild in
#                         (e.g. fedora-43-x86_64,fedora-rawhide-x86_64)
#     --without-check     skip the test suites in %check (faster iteration)
#     --release           force release naming even if HEAD is not the v<ver> tag
#
# Requires: git, cargo, rpm-build (rpmbuild); mock for --mock.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
spec="${repo_root}/packaging/rttx/rttx.spec"
outdir="${repo_root}/target/rpmbuild"
mock_chroots=""
force_release=0
rpmbuild_extra=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --outdir) outdir="$(mkdir -p "$2" && cd "$2" && pwd)"; shift 2 ;;
        --mock) mock_chroots="$2"; shift 2 ;;
        --without-check) rpmbuild_extra+=(--without check); shift ;;
        --release) force_release=1; shift ;;
        -h|--help) sed -n '2,25p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

for tool in git cargo rpmbuild; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "error: '$tool' not found (sudo dnf install rpm-build cargo git)" >&2
        exit 1
    }
done

cd "${repo_root}"

# --- Versions -----------------------------------------------------------------
version="$(cargo pkgid -p rttx-server | sed 's/.*[#@]//')"
spec_version="$(sed -n 's/^Version:[[:space:]]*//p' "${spec}")"
if [[ "${version}" != "${spec_version}" ]]; then
    echo "error: workspace version ${version} != spec Version ${spec_version}" >&2
    echo "       bump 'Version:' and add a %changelog entry in ${spec}" >&2
    exit 1
fi

commit="$(git rev-parse --short HEAD)"
snapinfo=""
if [[ ${force_release} -eq 0 ]] && ! git describe --tags --exact-match HEAD 2>/dev/null | grep -qx "v${version}"; then
    # Not building the release tag: mark it as a post-release snapshot so the
    # package version sorts above 1.0.0-1 and is obviously not the release.
    snapinfo=".$(git log -1 --format=%cd --date=format:%Y%m%d)git${commit}"
    echo "note: HEAD is not tag v${version}; building snapshot ${version}-1${snapinfo}"
fi
if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
    echo "warning: uncommitted changes are NOT included (git archive packs HEAD only)" >&2
fi

# --- Sources ------------------------------------------------------------------
sourcedir="${outdir}/SOURCES"
rm -rf "${sourcedir}"
mkdir -p "${sourcedir}" "${outdir}"

echo "Creating source tarball ${sourcedir}/rttx-${version}.tar.gz"
git archive --format=tar --prefix="rttx-${version}/" HEAD | gzip -n > "${sourcedir}/rttx-${version}.tar.gz"

echo "Vendoring crates (cargo vendor --locked)"
vendor_tmp="$(mktemp -d "${outdir}/vendor.XXXXXX")"
trap 'rm -rf "${vendor_tmp}"' EXIT
cargo vendor --locked "${vendor_tmp}/vendor" >/dev/null
# Reproducible tarball: fixed order, owner and mtime.
tar --sort=name --owner=0 --group=0 --numeric-owner --mtime='1970-01-01' \
    -C "${vendor_tmp}" -cf - vendor | xz -T0 -6 > "${sourcedir}/rttx-${version}-vendor.tar.xz"

# Bake the snapshot/commit info INTO the spec that goes in the SRPM. Anything
# passed with `--define` to `rpmbuild -bs` is not stored in the SRPM, so it
# would be lost when mock/COPR rebuild it.
{
    echo "# --- generated by packaging/rttx/rpm/build-srpm.sh; edit packaging/rttx/rttx.spec ---"
    echo "%global rttx_commit ${commit}"
    [[ -n "${snapinfo}" ]] && echo "%global snapinfo ${snapinfo}"
    echo
    cat "${spec}"
} > "${sourcedir}/rttx.spec"

# --- SRPM -----------------------------------------------------------------------
echo "Building SRPM"
rpmbuild -bs \
    --define "_sourcedir ${sourcedir}" \
    --define "_srcrpmdir ${outdir}" \
    --define "_specdir ${sourcedir}" \
    "${rpmbuild_extra[@]}" \
    "${sourcedir}/rttx.spec"

srpm="$(ls -t "${outdir}"/rttx-"${version}"-*.src.rpm | head -1)"
echo "SRPM: ${srpm}"

# --- Optional: rebuild in mock for each chroot ----------------------------------
if [[ -n "${mock_chroots}" ]]; then
    command -v mock >/dev/null 2>&1 || {
        echo "error: mock not found (sudo dnf install mock && sudo usermod -aG mock \$USER)" >&2
        exit 1
    }
    IFS=',' read -r -a chroots <<< "${mock_chroots}"
    for chroot in "${chroots[@]}"; do
        echo "==> mock rebuild in ${chroot}"
        mock -r "${chroot}" --rebuild "${srpm}" \
            --resultdir "${outdir}/${chroot}" \
            "${rpmbuild_extra[@]}"
        ls -1 "${outdir}/${chroot}"/*.rpm
    done
fi
