//! Shared protocol types for rttx-server and rttx GUI communication.
//!
//! All wire protocol messages are defined in `proto/rttx-v3.proto` and
//! generated by `prost-build`. This crate also provides helper functions for
//! UUID conversion and length-prefixed message framing.

use bytes::{Buf, BufMut, BytesMut};
use prost::Message;

/// Maximum message size (16 MB). Prevents unbounded allocations.
pub const MAX_MESSAGE_SIZE: u32 = 16 * 1024 * 1024;

/// Generated v3 protobuf types (RFC-021).
pub mod v3 {
    include!(concat!(env!("OUT_DIR"), "/rttx.v3.rs"));
}

/// V3 handshake: version negotiation, capability validation, message builders.
pub mod v3_handshake;

/// V3 envelope: request/response correlation and command classification.
pub mod v3_envelope;

/// V3 terminal mode state: builders and conversions (RFC-021 Section 5).
pub mod v3_terminal_modes;

/// V3 terminal input: builders and daemon-side resolution (RFC-021 Section 4).
pub mod v3_terminal_input;

/// V3 error model: typed `ProtocolError` builders and `ErrorKind` classification (RFC-021 Section 11).
pub mod v3_error;

/// V3 snapshot and output delta: builders and helpers (RFC-021 Sections 7–8).
pub mod v3_snapshot;

/// V3 workspace tree: server-authoritative tree, mutations, and viewport messages (RFC-031 §5).
pub mod v3_tree;

/// V3 chunked scrollback: builders, validation, and capability gating (RFC-021 Section 8, `OPT_CHUNKED_SCROLLBACK`).
pub mod v3_scrollback;

/// V3 resync: capability gating, builders, and overflow handling (RFC-021 Section 8, `OPT_RESYNC`).
pub mod v3_resync;

/// V3 workspace inventory: capability gating, builders, and field stripping (RFC-021 Section 9, `OPT_WORKSPACE_INVENTORY`).
pub mod v3_inventory;

/// V3 workspace takeover: capability gating, builders, and lease events (RFC-021 Section 10, `OPT_RUNTIME_TAKEOVER`).
pub mod v3_takeover;

/// V3 diagnostics: capability gating, builders, and report construction (RFC-021 Section 3, `OPT_DIAGNOSTICS`).
pub mod v3_diagnostics;

/// Convert a `uuid::Uuid` to protobuf bytes.
#[must_use]
pub fn uuid_to_bytes(id: uuid::Uuid) -> Vec<u8> {
    id.as_bytes().to_vec()
}

/// Convert protobuf bytes back to a `uuid::Uuid`.
///
/// # Errors
///
/// Returns an error if the byte slice is not exactly 16 bytes.
pub fn bytes_to_uuid(bytes: &[u8]) -> Result<uuid::Uuid, FrameError> {
    let arr: [u8; 16] = bytes.try_into().map_err(|_| FrameError::InvalidUuid(bytes.len()))?;
    Ok(uuid::Uuid::from_bytes(arr))
}

/// Errors that can occur during message framing.
#[derive(Debug, thiserror::Error)]
pub enum FrameError {
    /// The message exceeds the maximum allowed size.
    #[error("message too large: {0} bytes (max {MAX_MESSAGE_SIZE})")]
    TooLarge(u32),

    /// Not enough data to decode a complete frame.
    #[error("incomplete frame")]
    Incomplete,

    /// Protobuf decode error.
    #[error("decode error: {0}")]
    Decode(#[from] prost::DecodeError),

    /// Invalid UUID byte length.
    #[error("invalid UUID: expected 16 bytes, got {0}")]
    InvalidUuid(usize),
}

/// Encode a protobuf message with a 4-byte little-endian length prefix.
///
/// # Errors
///
/// Returns an error if the encoded message exceeds `MAX_MESSAGE_SIZE`.
pub fn encode_frame<M: Message>(msg: &M, buf: &mut BytesMut) -> Result<(), FrameError> {
    let len = msg.encoded_len();
    let len_u32 = u32::try_from(len).map_err(|_| FrameError::TooLarge(u32::MAX))?;
    if len_u32 > MAX_MESSAGE_SIZE {
        return Err(FrameError::TooLarge(len_u32));
    }
    buf.reserve(4 + len);
    buf.put_u32_le(len_u32);
    msg.encode(buf).map_err(|e| FrameError::Decode(prost::DecodeError::new(e.to_string())))?;
    Ok(())
}

/// Try to decode a length-prefixed frame from the buffer.
///
/// On success, advances the buffer past the consumed frame and returns the
/// decoded message. Returns `Err(FrameError::Incomplete)` if more data is
/// needed.
///
/// # Errors
///
/// Returns an error on size violations, incomplete data, or decode failures.
pub fn decode_frame<M: Message + Default>(buf: &mut BytesMut) -> Result<M, FrameError> {
    if buf.len() < 4 {
        return Err(FrameError::Incomplete);
    }
    let len = u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]);
    if len > MAX_MESSAGE_SIZE {
        return Err(FrameError::TooLarge(len));
    }
    let total = 4 + len as usize;
    if buf.len() < total {
        return Err(FrameError::Incomplete);
    }
    buf.advance(4);
    let msg = M::decode(buf.split_to(len as usize))?;
    Ok(msg)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uuid_roundtrip() {
        let id = uuid::Uuid::new_v4();
        let bytes = uuid_to_bytes(id);
        let recovered = bytes_to_uuid(&bytes).unwrap();
        assert_eq!(id, recovered);
    }

    #[test]
    fn uuid_invalid_length() {
        assert!(bytes_to_uuid(&[0; 5]).is_err());
    }

    // RFC-031 Step 6 renamed the v3 `Runtime*` types/enums to `Workspace*`.
    // The rename must be wire-compatible: protobuf serializes enums by their
    // integer value, so the renamed variants must keep their original numbers
    // or a renamed daemon would silently misread a peer built before the
    // rename (and persisted snapshots would decode wrong). Pin the values.
    #[test]
    fn renamed_workspace_enums_preserve_wire_values() {
        assert_eq!(v3::WorkspacePolicy::Persistent as i32, 1);
        assert_eq!(v3::WorkspacePolicy::Ephemeral as i32, 2);
        assert_eq!(v3::WorkspaceAttachMode::ReadWrite as i32, 1);
        assert_eq!(v3::WorkspaceAttachMode::ReadOnly as i32, 2);
        assert_eq!(v3::WorkspaceClientRole::Writer as i32, 2);
        assert_eq!(v3::WorkspaceClientRole::Reader as i32, 3);
        assert_eq!(v3::WorkspaceTerminationReason::Explicit as i32, 1);
        assert_eq!(v3::WorkspaceTerminationReason::EphemeralDetach as i32, 2);
        assert_eq!(v3::Capability::CoreWorkspaceLifecycle as i32, 1);
        assert_eq!(v3::Capability::OptWorkspaceInventory as i32, 100);
        assert_eq!(v3::Capability::OptWorkspaceTakeover as i32, 101);
        assert_eq!(v3::ErrorKind::WorkspaceNotFound as i32, 4);
    }

    // A renamed lifecycle command must still occupy its original envelope
    // field tag so it round-trips on the wire unchanged.
    #[test]
    fn renamed_create_workspace_command_roundtrips_on_wire() {
        let msg = v3::ClientEnvelope {
            request_id: 7,
            command: Some(v3::client_envelope::Command::CreateWorkspace(v3::CreateWorkspace {
                name: "alpha".into(),
                policy: v3::WorkspacePolicy::Persistent as i32,
            })),
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::ClientEnvelope = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }
}

#[cfg(test)]
mod v3_tests {
    use super::*;

    fn rid() -> Vec<u8> {
        uuid_to_bytes(uuid::Uuid::new_v4())
    }

    fn pid() -> Vec<u8> {
        uuid_to_bytes(uuid::Uuid::new_v4())
    }

    // ── Handshake roundtrips ──

    #[test]
    fn v3_client_hello_roundtrip() {
        let msg = v3::ClientHello {
            min_protocol_version: 3,
            max_protocol_version: 3,
            client_id: rid(),
            client_name: "rttx".into(),
            client_version: "0.4.0".into(),
            capabilities: vec![
                v3::Capability::CoreWorkspaceLifecycle as i32,
                v3::Capability::CorePaneLifecycle as i32,
                v3::Capability::CoreTerminalIo as i32,
                v3::Capability::CoreTerminalModes as i32,
                v3::Capability::CorePasteIntent as i32,
                v3::Capability::CoreFocusEvents as i32,
                v3::Capability::OptDiagnostics as i32,
            ],
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::ClientHello = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    #[test]
    fn v3_server_hello_roundtrip() {
        let msg = v3::ServerHello {
            negotiated_protocol_version: 3,
            server_id: rid(),
            server_version: "0.4.0".into(),
            capabilities: vec![
                v3::Capability::CoreWorkspaceLifecycle as i32,
                v3::Capability::CorePaneLifecycle as i32,
            ],
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::ServerHello = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    // ── Capability enum values match RFC ──

    #[test]
    fn v3_capability_enum_values() {
        assert_eq!(v3::Capability::Unspecified as i32, 0);
        assert_eq!(v3::Capability::CoreWorkspaceLifecycle as i32, 1);
        assert_eq!(v3::Capability::CorePaneLifecycle as i32, 2);
        assert_eq!(v3::Capability::CoreTerminalIo as i32, 3);
        assert_eq!(v3::Capability::CoreTerminalModes as i32, 4);
        assert_eq!(v3::Capability::CorePasteIntent as i32, 5);
        assert_eq!(v3::Capability::CoreFocusEvents as i32, 6);
        assert_eq!(v3::Capability::OptWorkspaceInventory as i32, 100);
        assert_eq!(v3::Capability::OptWorkspaceTakeover as i32, 101);
        assert_eq!(v3::Capability::OptResync as i32, 102);
        assert_eq!(v3::Capability::OptChunkedScrollback as i32, 103);
        assert_eq!(v3::Capability::OptDiagnostics as i32, 104);
    }

    // ── Enum zero values ──

    #[test]
    fn v3_enum_zero_values() {
        assert_eq!(v3::WorkspacePolicy::Unspecified as i32, 0);
        assert_eq!(v3::WorkspaceAttachMode::Unspecified as i32, 0);
        assert_eq!(v3::WorkspaceClientRole::Unspecified as i32, 0);
        assert_eq!(v3::WorkspaceTerminationReason::Unspecified as i32, 0);
        assert_eq!(v3::MouseMode::None as i32, 0);
        assert_eq!(v3::ErrorKind::Unspecified as i32, 0);
    }

    // ── Error kind enum values match RFC ──

    #[test]
    fn v3_error_kind_values() {
        assert_eq!(v3::ErrorKind::ProtocolMismatch as i32, 1);
        assert_eq!(v3::ErrorKind::UnsupportedCapability as i32, 2);
        assert_eq!(v3::ErrorKind::InvalidArgument as i32, 3);
        assert_eq!(v3::ErrorKind::WorkspaceNotFound as i32, 4);
        assert_eq!(v3::ErrorKind::PaneNotFound as i32, 5);
        assert_eq!(v3::ErrorKind::OwnershipConflict as i32, 6);
        assert_eq!(v3::ErrorKind::TakeoverRequired as i32, 7);
        assert_eq!(v3::ErrorKind::StreamOverflow as i32, 8);
        assert_eq!(v3::ErrorKind::Internal as i32, 9);
    }

    // ── TerminalModeState roundtrip ──

    #[test]
    fn v3_terminal_mode_state_roundtrip() {
        let msg = v3::TerminalModeState {
            bracketed_paste: true,
            focus_reporting: true,
            application_cursor_keys: false,
            application_keypad: true,
            alternate_screen: true,
            cursor_hidden: false,
            mouse_mode: v3::MouseMode::Any as i32,
            sgr_mouse: true,
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::TerminalModeState = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    // ── TerminalInput variants ──

    #[test]
    fn v3_terminal_input_raw_roundtrip() {
        let msg = v3::TerminalInput {
            runtime_id: rid(),
            pane_id: pid(),
            kind: Some(v3::terminal_input::Kind::Raw(v3::RawInput {
                data: bytes::Bytes::from_static(b"hello"),
            })),
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::TerminalInput = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    #[test]
    fn v3_terminal_input_paste_roundtrip() {
        let msg = v3::TerminalInput {
            runtime_id: rid(),
            pane_id: pid(),
            kind: Some(v3::terminal_input::Kind::Paste(v3::PasteInput {
                text: bytes::Bytes::from_static(b"pasted text"),
            })),
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::TerminalInput = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    #[test]
    fn v3_terminal_input_focus_roundtrip() {
        let msg = v3::TerminalInput {
            runtime_id: rid(),
            pane_id: pid(),
            kind: Some(v3::terminal_input::Kind::Focus(v3::FocusInput { focused: true })),
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::TerminalInput = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    // ── ProtocolError roundtrip ──

    #[test]
    fn v3_protocol_error_roundtrip() {
        let msg = v3::ProtocolError {
            kind: v3::ErrorKind::WorkspaceNotFound as i32,
            message: "workspace abc not found".into(),
            operation: "AttachWorkspace".into(),
            retryable: false,
            user_action_required: true,
            retry_after_seconds: 0,
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::ProtocolError = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    // ── Snapshot roundtrip ──

    #[test]
    fn v3_workspace_snapshot_roundtrip() {
        let msg = v3::WorkspaceSnapshot {
            runtime_id: rid(),
            workspace_revision: 42,
            client_role: v3::WorkspaceClientRole::Writer as i32,
            panes: vec![v3::PaneSnapshot {
                pane_id: pid(),
                pane_output_seq: 100,
                title: "bash".into(),
                cwd: "/home/user".into(),
                cols: 120,
                rows: 40,
                exit_status: None,
                terminal_modes: Some(v3::TerminalModeState {
                    bracketed_paste: true,
                    focus_reporting: false,
                    application_cursor_keys: false,
                    application_keypad: false,
                    alternate_screen: false,
                    cursor_hidden: false,
                    mouse_mode: v3::MouseMode::None as i32,
                    sgr_mouse: false,
                }),
                scrollback_tail: bytes::Bytes::from_static(b"$ ls\nfile.txt\n"),
                total_scrollback_bytes: 4096,
                scrollback_complete: false,
            }],
            tree: None,
            default_active_pane_id: Vec::new(),
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::WorkspaceSnapshot = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    // ── Scrollback roundtrip ──

    #[test]
    fn v3_scrollback_roundtrip() {
        let rt = rid();
        let pn = pid();
        let req = v3::GetScrollback {
            runtime_id: rt.clone(),
            pane_id: pn.clone(),
            offset: 0,
            limit: 65536,
        };
        let mut buf = BytesMut::new();
        encode_frame(&req, &mut buf).unwrap();
        let decoded: v3::GetScrollback = decode_frame(&mut buf).unwrap();
        assert_eq!(req, decoded);

        let chunk = v3::ScrollbackChunk {
            runtime_id: rt,
            pane_id: pn,
            offset: 0,
            data: bytes::Bytes::from_static(b"scrollback data"),
            is_last: true,
        };
        let mut buf = BytesMut::new();
        encode_frame(&chunk, &mut buf).unwrap();
        let decoded: v3::ScrollbackChunk = decode_frame(&mut buf).unwrap();
        assert_eq!(chunk, decoded);
    }

    // ── StreamOverflow roundtrip ──

    #[test]
    fn v3_stream_overflow_roundtrip() {
        for pane_id in [Some(pid()), None] {
            let msg = v3::StreamOverflow { runtime_id: rid(), pane_id, dropped_count: 42 };
            let mut buf = BytesMut::new();
            encode_frame(&msg, &mut buf).unwrap();
            let decoded: v3::StreamOverflow = decode_frame(&mut buf).unwrap();
            assert_eq!(msg, decoded);
        }
    }
}

#[cfg(test)]
mod v3_envelope_tests {
    use super::*;

    fn rid() -> Vec<u8> {
        uuid_to_bytes(uuid::Uuid::new_v4())
    }

    fn pid() -> Vec<u8> {
        uuid_to_bytes(uuid::Uuid::new_v4())
    }

    #[test]
    fn v3_client_envelope_all_commands() {
        let rt = rid();
        let pn = pid();

        let envelopes: Vec<v3::ClientEnvelope> = vec![
            // Terminal I/O
            v3::ClientEnvelope {
                request_id: 0,
                command: Some(v3::client_envelope::Command::TerminalInput(v3::TerminalInput {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    kind: Some(v3::terminal_input::Kind::Raw(v3::RawInput {
                        data: bytes::Bytes::from_static(b"x"),
                    })),
                })),
            },
            // Control
            v3::ClientEnvelope {
                request_id: 1,
                command: Some(v3::client_envelope::Command::Ping(v3::Ping { nonce: 7 })),
            },
            v3::ClientEnvelope {
                request_id: 0,
                command: Some(v3::client_envelope::Command::Shutdown(v3::Shutdown {})),
            },
            // Workspace lifecycle
            v3::ClientEnvelope {
                request_id: 2,
                command: Some(v3::client_envelope::Command::CreateWorkspace(v3::CreateWorkspace {
                    name: "dev".into(),
                    policy: v3::WorkspacePolicy::Persistent as i32,
                })),
            },
            v3::ClientEnvelope {
                request_id: 3,
                command: Some(v3::client_envelope::Command::AttachWorkspace(v3::AttachWorkspace {
                    runtime_id: rt.clone(),
                    attach_mode: v3::WorkspaceAttachMode::ReadWrite as i32,
                })),
            },
            v3::ClientEnvelope {
                request_id: 4,
                command: Some(v3::client_envelope::Command::DetachWorkspace(v3::DetachWorkspace {
                    runtime_id: rt.clone(),
                })),
            },
            v3::ClientEnvelope {
                request_id: 5,
                command: Some(v3::client_envelope::Command::TerminateWorkspace(
                    v3::TerminateWorkspace { runtime_id: rt.clone() },
                )),
            },
            v3::ClientEnvelope {
                request_id: 6,
                command: Some(v3::client_envelope::Command::RenameWorkspace(v3::RenameWorkspace {
                    runtime_id: rt.clone(),
                    name: "prod".into(),
                })),
            },
            v3::ClientEnvelope {
                request_id: 7,
                command: Some(v3::client_envelope::Command::ListWorkspaces(v3::ListWorkspaces {})),
            },
            // Pane lifecycle
            v3::ClientEnvelope {
                request_id: 8,
                command: Some(v3::client_envelope::Command::CreatePane(v3::CreatePane {
                    runtime_id: rt.clone(),
                    cwd: Some("/tmp".into()),
                    dark_background: Some(true),
                    cols: 80,
                    rows: 24,
                    no_persist: None,
                })),
            },
            v3::ClientEnvelope {
                request_id: 9,
                command: Some(v3::client_envelope::Command::ClosePane(v3::ClosePane {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                })),
            },
            v3::ClientEnvelope {
                request_id: 0,
                command: Some(v3::client_envelope::Command::ResizePane(v3::ResizePane {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    cols: 132,
                    rows: 43,
                })),
            },
            v3::ClientEnvelope {
                request_id: 0,
                command: Some(v3::client_envelope::Command::SetPaneTitle(v3::SetPaneTitle {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    title: "my pane".into(),
                })),
            },
            // Recovery
            v3::ClientEnvelope {
                request_id: 10,
                command: Some(v3::client_envelope::Command::ResyncWorkspace(v3::ResyncWorkspace {
                    runtime_id: rt.clone(),
                })),
            },
            // Scrollback
            v3::ClientEnvelope {
                request_id: 11,
                command: Some(v3::client_envelope::Command::GetScrollback(v3::GetScrollback {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    offset: 0,
                    limit: 262_144,
                })),
            },
            // Diagnostics
            v3::ClientEnvelope {
                request_id: 12,
                command: Some(v3::client_envelope::Command::GetDiagnostics(v3::GetDiagnostics {})),
            },
            // Takeover (OPT_RUNTIME_TAKEOVER)
            v3::ClientEnvelope {
                request_id: 13,
                command: Some(v3::client_envelope::Command::TakeoverWorkspace(
                    v3::TakeoverWorkspace { runtime_id: rt.clone() },
                )),
            },
        ];

        for env in &envelopes {
            let mut buf = BytesMut::new();
            encode_frame(env, &mut buf).unwrap();
            let decoded: v3::ClientEnvelope = decode_frame(&mut buf).unwrap();
            assert_eq!(env, &decoded);
        }
    }

    #[test]
    fn v3_server_envelope_all_payloads() {
        let rt = rid();
        let pn = pid();

        let envelopes: Vec<v3::ServerEnvelope> = vec![
            // Terminal I/O
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::OutputDelta(v3::OutputDelta {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    data: bytes::Bytes::from_static(b"output"),
                    pane_output_seq: 1,
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::TerminalModeChanged(
                    v3::TerminalModeChanged {
                        runtime_id: rt.clone(),
                        pane_id: pn.clone(),
                        workspace_revision: 5,
                        modes: Some(v3::TerminalModeState {
                            bracketed_paste: true,
                            ..Default::default()
                        }),
                    },
                )),
            },
            // Control
            v3::ServerEnvelope {
                request_id: 1,
                payload: Some(v3::server_envelope::Payload::Pong(v3::Pong { nonce: 7 })),
            },
            // Workspace lifecycle
            v3::ServerEnvelope {
                request_id: 2,
                payload: Some(v3::server_envelope::Payload::WorkspaceCreated(
                    v3::WorkspaceCreated { runtime_id: rt.clone(), workspace_revision: 1 },
                )),
            },
            v3::ServerEnvelope {
                request_id: 3,
                payload: Some(v3::server_envelope::Payload::WorkspaceSnapshot(
                    v3::WorkspaceSnapshot {
                        runtime_id: rt.clone(),
                        workspace_revision: 10,
                        client_role: v3::WorkspaceClientRole::Writer as i32,
                        panes: vec![],
                        tree: None,
                        default_active_pane_id: Vec::new(),
                    },
                )),
            },
            v3::ServerEnvelope {
                request_id: 4,
                payload: Some(v3::server_envelope::Payload::WorkspaceDetached(
                    v3::WorkspaceDetached { runtime_id: rt.clone(), workspace_revision: 11 },
                )),
            },
            v3::ServerEnvelope {
                request_id: 5,
                payload: Some(v3::server_envelope::Payload::WorkspaceTerminated(
                    v3::WorkspaceTerminated {
                        runtime_id: rt.clone(),
                        final_revision: 12,
                        reason: v3::WorkspaceTerminationReason::Explicit as i32,
                    },
                )),
            },
            v3::ServerEnvelope {
                request_id: 6,
                payload: Some(v3::server_envelope::Payload::WorkspaceRenamed(
                    v3::WorkspaceRenamed {
                        runtime_id: rt.clone(),
                        name: "renamed".into(),
                        workspace_revision: 13,
                    },
                )),
            },
            v3::ServerEnvelope {
                request_id: 7,
                payload: Some(v3::server_envelope::Payload::WorkspaceList(v3::WorkspaceList {
                    workspaces: vec![],
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::AttachBlocked(v3::AttachBlocked {
                    runtime_id: rt.clone(),
                    current_client_role: v3::WorkspaceClientRole::Unattached as i32,
                    attached_client_count: 1,
                    read_only_client_count: 0,
                })),
            },
            // Pane lifecycle
            v3::ServerEnvelope {
                request_id: 8,
                payload: Some(v3::server_envelope::Payload::PaneCreated(v3::PaneCreated {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    workspace_revision: 14,
                })),
            },
            v3::ServerEnvelope {
                request_id: 9,
                payload: Some(v3::server_envelope::Payload::PaneClosed(v3::PaneClosed {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    workspace_revision: 15,
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::PaneResized(v3::PaneResized {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    cols: 100,
                    rows: 30,
                    workspace_revision: 16,
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::PaneExited(v3::PaneExited {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    status: 0,
                    workspace_revision: 17,
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::TitleChanged(v3::TitleChanged {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    title: "new title".into(),
                    workspace_revision: 18,
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::CwdChanged(v3::CwdChanged {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    cwd: "/home".into(),
                    workspace_revision: 19,
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::Bell(v3::Bell {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                })),
            },
            // Recovery
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::StreamOverflow(v3::StreamOverflow {
                    runtime_id: rt.clone(),
                    pane_id: Some(pn.clone()),
                    dropped_count: 5,
                })),
            },
            // Scrollback
            v3::ServerEnvelope {
                request_id: 11,
                payload: Some(v3::server_envelope::Payload::ScrollbackChunk(v3::ScrollbackChunk {
                    runtime_id: rt.clone(),
                    pane_id: pn.clone(),
                    offset: 0,
                    data: bytes::Bytes::from_static(b"chunk"),
                    is_last: true,
                })),
            },
            // Diagnostics
            v3::ServerEnvelope {
                request_id: 12,
                payload: Some(v3::server_envelope::Payload::DiagnosticsReport(
                    v3::DiagnosticsReport {
                        workspace_count: 1,
                        total_pane_count: 2,
                        total_active_panes: 2,
                        total_exited_panes: 0,
                        client_count: 1,
                        pty_writer_count: 1,
                        total_raw_bytes: 1024,
                        total_pending_flush: 0,
                        workspaces: vec![],
                    },
                )),
            },
            // Error
            v3::ServerEnvelope {
                request_id: 99,
                payload: Some(v3::server_envelope::Payload::Error(v3::ProtocolError {
                    kind: v3::ErrorKind::WorkspaceNotFound as i32,
                    message: "not found".into(),
                    operation: "AttachWorkspace".into(),
                    retryable: false,
                    user_action_required: false,
                    retry_after_seconds: 0,
                })),
            },
            // Takeover events (OPT_RUNTIME_TAKEOVER)
            v3::ServerEnvelope {
                request_id: 13,
                payload: Some(v3::server_envelope::Payload::TakeoverCompleted(
                    v3::TakeoverCompleted { runtime_id: rt.clone(), workspace_revision: 50 },
                )),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::LeaseLost(v3::LeaseLost {
                    runtime_id: rt.clone(),
                    workspace_revision: 51,
                    new_owner_id: rid(),
                })),
            },
            v3::ServerEnvelope {
                request_id: 0,
                payload: Some(v3::server_envelope::Payload::OwnerDisconnected(
                    v3::OwnerDisconnected { runtime_id: rt.clone(), workspace_revision: 52 },
                )),
            },
        ];

        for env in &envelopes {
            let mut buf = BytesMut::new();
            encode_frame(env, &mut buf).unwrap();
            let decoded: v3::ServerEnvelope = decode_frame(&mut buf).unwrap();
            assert_eq!(env, &decoded);
        }
    }

    #[test]
    fn v3_envelope_field_numbers_match_rfc() {
        // Verify high-frequency paths use single-byte tags (field < 16).
        // TerminalInput is field 2 in ClientEnvelope.
        let env = v3::ClientEnvelope {
            request_id: 0,
            command: Some(v3::client_envelope::Command::TerminalInput(v3::TerminalInput {
                runtime_id: rid(),
                pane_id: pid(),
                kind: Some(v3::terminal_input::Kind::Raw(v3::RawInput {
                    data: bytes::Bytes::from_static(b"a"),
                })),
            })),
        };
        let mut buf = BytesMut::new();
        encode_frame(&env, &mut buf).unwrap();
        // OutputDelta is field 2, TerminalModeChanged is field 3 in ServerEnvelope.
        let senv = v3::ServerEnvelope {
            request_id: 0,
            payload: Some(v3::server_envelope::Payload::OutputDelta(v3::OutputDelta {
                runtime_id: rid(),
                pane_id: pid(),
                data: bytes::Bytes::from_static(b"b"),
                pane_output_seq: 1,
            })),
        };
        let mut buf2 = BytesMut::new();
        encode_frame(&senv, &mut buf2).unwrap();
        // Both encode successfully — field numbers are valid.
        let decoded: v3::ClientEnvelope = decode_frame(&mut buf).unwrap();
        assert_eq!(env, decoded);
        let decoded: v3::ServerEnvelope = decode_frame(&mut buf2).unwrap();
        assert_eq!(senv, decoded);
    }

    #[test]
    fn v3_workspace_info_inventory_fields() {
        let msg = v3::WorkspaceInfo {
            id: rid(),
            name: "dev-workspace".into(),
            policy: v3::WorkspacePolicy::Persistent as i32,
            pane_count: 3,
            has_write_owner: true,
            read_only_client_count: 1,
            current_client_role: v3::WorkspaceClientRole::Writer as i32,
            workspace_revision: 42,
            reconstructed: false,
            user_renamed: false,
            active_pane_summary: "bash, vim, htop".into(),
            takeover_eligible: true,
            disabled_reason: String::new(),
            panes: vec![v3::PaneInfo {
                id: pid(),
                title: "bash".into(),
                cwd: "/home/user".into(),
                cols: 80,
                rows: 24,
                exit_status: None,
                reconstructed: false,
                no_persist: false,
            }],
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::WorkspaceInfo = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    #[test]
    fn v3_workspace_termination_ephemeral_detach() {
        let msg = v3::WorkspaceTerminated {
            runtime_id: rid(),
            final_revision: 99,
            reason: v3::WorkspaceTerminationReason::EphemeralDetach as i32,
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::WorkspaceTerminated = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }

    #[test]
    fn v3_mouse_mode_values() {
        assert_eq!(v3::MouseMode::None as i32, 0);
        assert_eq!(v3::MouseMode::X10 as i32, 1);
        assert_eq!(v3::MouseMode::Normal as i32, 2);
        assert_eq!(v3::MouseMode::Button as i32, 3);
        assert_eq!(v3::MouseMode::Any as i32, 4);
    }

    #[test]
    fn v3_pane_snapshot_with_all_modes() {
        let msg = v3::PaneSnapshot {
            pane_id: pid(),
            pane_output_seq: 500,
            title: "vim".into(),
            cwd: "/project".into(),
            cols: 120,
            rows: 40,
            exit_status: Some(0),
            terminal_modes: Some(v3::TerminalModeState {
                bracketed_paste: true,
                focus_reporting: true,
                application_cursor_keys: true,
                application_keypad: true,
                alternate_screen: true,
                cursor_hidden: true,
                mouse_mode: v3::MouseMode::Any as i32,
                sgr_mouse: true,
            }),
            scrollback_tail: bytes::Bytes::from_static(b"scrollback"),
            total_scrollback_bytes: 1_000_000,
            scrollback_complete: false,
        };
        let mut buf = BytesMut::new();
        encode_frame(&msg, &mut buf).unwrap();
        let decoded: v3::PaneSnapshot = decode_frame(&mut buf).unwrap();
        assert_eq!(msg, decoded);
    }
}
